import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {campuses,sources} from './data.js';
const $=s=>document.querySelector(s), colors={'教学科研':0x8faabb,'公共文化':0x42a9aa,'生活服务':0xc6b393,'体育':0x6f9fb8};
let campus=campuses[0],selected=null,filter='全部',mode='3d',renderer,scene,camera,controls,group,meshes=[],pins=[],generation=0;
let flatScale=1,flatX=0,flatY=0,drag=null,flatW=1000,flatH=1000;
const area=$('.map-area'), root=$('#scene');
function center(b){const xs=b.poly.map(p=>p[0]),ys=b.poly.map(p=>p[1]);return [(Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2];}
function world(x,y){const [cx,cy,w,h]=campus.crop;return [(x-cx-w/2)*1000/h,(y-cy-h/2)*1000/h];}
function matches(b){const q=$('#search').value.trim().toLowerCase();return (filter==='全部'||b.type===filter)&&(!q||`${b.name} ${b.id} ${b.type}`.toLowerCase().includes(q));}
function list(){const all=campus.buildings.filter(matches);$('#result-count').textContent=all.length+' 处';$('#places').replaceChildren();if(!all.length)$('#places').innerHTML='<p class="empty">没有找到匹配地点，试试其他名称或编号。</p>';all.forEach((b,i)=>{const el=document.createElement('button');el.className='place'+(selected===b?' selected':'');el.innerHTML=`<span class="num">${String(i+1).padStart(2,'0')}</span><span><strong>${b.name}</strong><small>${b.type} · ${b.id}</small></span><span class="arrow">↗</span>`;el.onclick=()=>select(b,true);$('#places').append(el);});for(const m of meshes){m.material.opacity=matches(m.userData.b)?1:.2;m.material.transparent=!matches(m.userData.b);}for(const p of pins)p.el.classList.toggle('selected',p.b===selected);}
function select(b,focus=false){selected=b;const s=sources[b.verifiedSource??campus.source];$('#detail').hidden=false;$('#detail').innerHTML=`<button class="close" aria-label="关闭地点详情">×</button><span class="tag">${b.type} · ${b.id}</span><h2>${b.name}</h2>${b.photo?`<img class="building-photo" src="assets/${b.photo}" alt="${b.name}官方实景参考"><a href="${sources[b.photoSource].url}" target="_blank" rel="noopener">实景照片来源 ↗</a>`:''}<p>${b.description||`位置及名称依据${campus.mapYear}，可切换官方地图对照。`}</p><div class="evidence">平面：官方图人工描摹<br>高度：示意，非实测<br>范围：外部体块，无室内导航</div><a href="${s.url}" target="_blank" rel="noopener">查看官方依据 ↗</a>`;$('#detail .close').onclick=()=>{selected=null;$('#detail').hidden=true;list();};list();if(focus){const [x,y]=center(b);if(mode==='3d'&&controls){const [wx,wz]=world(x,y),delta=new THREE.Vector3(wx,0,wz).sub(controls.target);controls.target.add(delta);camera.position.add(delta);}else{const [cx,cy,w,h]=campus.crop;flatX=area.clientWidth*.4-(x-cx)/w*flatW*flatScale;flatY=area.clientHeight*.55-(y-cy)/h*flatH*flatScale;updateFlat();}}}
function buildPins(){pins.forEach(p=>p.el.remove());pins=[];$('#flat-markers').replaceChildren();campus.buildings.forEach((b,i)=>{const [x,y]=center(b),[wx,wz]=world(x,y);const el=document.createElement('button');el.className='pin';el.textContent=b.name;el.setAttribute('aria-label','查看'+b.name);el.onclick=()=>select(b);$('#labels').append(el);pins.push({b,el,pos:new THREE.Vector3(wx,27,wz),i});const f=el.cloneNode(true);const [cx,cy,w,h]=campus.crop;f.style.left=((x-cx)/w*100)+'%';f.style.top=((y-cy)/h*100)+'%';f.onclick=()=>select(b);f.dataset.id=b.id;$('#flat-markers').append(f);});}
function disposeGroup(){if(!group)return;group.traverse(o=>{o.geometry?.dispose();if(o.material){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{m.map?.dispose();m.dispose();});}});scene.remove(group);}
function renderMap(texture){if(!renderer)return;disposeGroup();group=new THREE.Group();scene.add(group);meshes=[];const [, ,w,h]=campus.crop,width=w/h*1000;
 const base=new THREE.Mesh(new THREE.BoxGeometry(width+12,12,1012),new THREE.MeshStandardMaterial({color:0xc1d1dc,roughness:.9}));base.position.y=-7;group.add(base);
 const plane=new THREE.Mesh(new THREE.PlaneGeometry(width,1000),new THREE.MeshStandardMaterial({map:texture,roughness:1,color:0xffffff}));plane.rotation.x=-Math.PI/2;plane.position.y=.1;plane.receiveShadow=true;group.add(plane);
 campus.buildings.forEach(b=>{const pts=b.poly.map(([x,y])=>world(x,y));const shape=new THREE.Shape();shape.moveTo(pts[0][0],-pts[0][1]);pts.slice(1).forEach(p=>shape.lineTo(p[0],-p[1]));shape.closePath();const height=20;
 const geo=new THREE.ExtrudeGeometry(shape,{depth:height,bevelEnabled:false});geo.rotateX(-Math.PI/2);const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:colors[b.type],roughness:.72,metalness:.05}));mesh.position.y=.3;mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.b=b;group.add(mesh);meshes.push(mesh);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:0xf8fbff,transparent:true,opacity:.55}));edge.position.y=.35;group.add(edge);});reset();list();}
async function changeCampus(index){const token=++generation;campus=campuses[index];selected=null;filter='全部';$('#search').value='';$('#detail').hidden=true;$('#campus-title').textContent=campus.name;$('#campus-number').textContent=`0${index+1} / 03`;$('#campus-intro').textContent=campus.intro;$('#address').textContent='⌖ '+campus.address;$('#map-source').textContent=campus.mapYear+' · 来源：北航';document.querySelectorAll('#campus-tabs button').forEach((e,i)=>{e.classList.toggle('active',i===index);e.setAttribute('aria-pressed',String(i===index));});$('#filters').replaceChildren();['全部','教学科研','公共文化','生活服务','体育'].forEach(t=>{const e=document.createElement('button');e.textContent=t;e.classList.toggle('active',t===filter);e.onclick=()=>{filter=t;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x.textContent===t));list();updateFlat();};$('#filters').append(e);});list();$('#loading').hidden=false;$('#loading').textContent='正在载入校园地图…';
 try{const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src='assets/'+campus.image;});if(token!==generation)return;const [cx,cy,w,h]=campus.crop;const canvas=document.createElement('canvas');canvas.width=w*1.6;canvas.height=h*1.6;const ctx=canvas.getContext('2d');const rx=img.naturalWidth/campus.size[0],ry=img.naturalHeight/campus.size[1];ctx.drawImage(img,cx*rx,cy*ry,w*rx,h*ry,0,0,canvas.width,canvas.height);$('#flat-image').src=canvas.toDataURL('image/jpeg',.95);$('#flat-image').alt=campus.name+'官方地图（校园区域裁切，完整原图见资料）';flatW=w;flatH=h;$('#flat-inner').style.width=w+'px';$('#flat-inner').style.height=h+'px';buildPins();const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=renderer?Math.min(8,renderer.capabilities.getMaxAnisotropy()):1;renderMap(texture);resetFlat();$('#loading').hidden=true;}catch(e){if(token===generation){$('#loading').textContent='地图载入失败，请刷新重试；资料面板仍可打开官方原图。';console.error(e);}}}
function init3d(){try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;root.append(renderer.domElement);scene=new THREE.Scene();scene.background=new THREE.Color(0xe6edf2);camera=new THREE.PerspectiveCamera(38,1,1,6000);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.maxPolarAngle=Math.PI*.47;controls.minDistance=140;controls.maxDistance=2700;controls.target.set(0,0,0);scene.add(new THREE.HemisphereLight(0xf5fbff,0xa2b6c1,2.7));const light=new THREE.DirectionalLight(0xfff8eb,2.3);light.position.set(-500,900,-350);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-850,right:850,top:850,bottom:-850,near:1,far:2500});light.shadow.bias=-.0005;scene.add(light);const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down;renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(meshes).find(o=>matches(o.object.userData.b));if(hit)select(hit.object.userData.b);});new ResizeObserver(resize).observe(area);resize();animate();}catch(e){console.warn('WebGL unavailable; official map fallback.',e);renderer=null;mode='2d';$('#view3d').disabled=true;$('#view3d').title='此设备不支持WebGL，已显示官方地图';setMode('2d');}}
function resize(){if(renderer){renderer.setSize(area.clientWidth,area.clientHeight);camera.aspect=area.clientWidth/area.clientHeight;camera.updateProjectionMatrix();}if(mode==='2d')resetFlat();}
function reset(){if(!camera)return;controls.target.set(0,0,0);const d=camera.aspect<.9?1550:1180;camera.position.set(500,d,880);controls.update();}
function animate(){requestAnimationFrame(animate);if(mode!=='3d'||!renderer)return;controls.update();renderer.render(scene,camera);const occupied=[];const candidates=[...pins].sort((a,b)=>(b.b===selected)-(a.b===selected)||a.i-b.i);for(const p of candidates){const v=p.pos.clone().project(camera),x=(v.x*.5+.5)*area.clientWidth,y=(-v.y*.5+.5)*area.clientHeight;let show=matches(p.b)&&v.z<1&&v.z>-1&&x>0&&x<area.clientWidth&&y>75&&y<area.clientHeight-48;const width=p.el.offsetWidth||90,box=[x-width/2,y-30,x+width/2,y];if(show&&p.b!==selected&&occupied.some(r=>box[0]<r[2]+10&&box[2]>r[0]-10&&box[1]<r[3]+8&&box[3]>r[1]-8))show=false;p.el.hidden=!show;if(show){p.el.style.left=x+'px';p.el.style.top=y+'px';occupied.push(box);}}}
function setMode(m){mode=m;root.hidden=m!=='3d';$('#labels').hidden=m!=='3d';$('#flat').hidden=m!=='2d';$('#view3d').setAttribute('aria-pressed',String(m==='3d'));$('#view2d').setAttribute('aria-pressed',String(m==='2d'));$('#map-status').textContent=m==='3d'?'参考体块 · 高度示意':'官方原图 · 可缩放';$('#map-hint').textContent=m==='3d'?'拖动旋转 · 滚轮缩放 · 右键平移':'拖动平移 · 滚轮缩放 · 点击地点查看';if(m==='2d')resetFlat();}
function updateFlat(){$('#flat-inner').style.transform=`translate(${flatX}px,${flatY}px) scale(${flatScale})`;$('#flat-markers').querySelectorAll('.pin').forEach(e=>{const b=campus.buildings.find(b=>b.id===e.dataset.id);e.hidden=!matches(b);e.classList.toggle('selected',b===selected);e.style.transform=`translate(-50%,-100%) scale(${1/flatScale})`;});}
function resetFlat(){flatScale=Math.min((area.clientWidth-80)/flatW,(area.clientHeight-125)/flatH);flatX=(area.clientWidth-flatW*flatScale)/2;flatY=75+(area.clientHeight-125-flatH*flatScale)/2;updateFlat();}
function zoom(f,x=area.clientWidth/2,y=area.clientHeight/2){if(mode==='3d'&&camera){camera.position.sub(controls.target).multiplyScalar(1/f).add(controls.target);return;}const next=Math.max(.15,Math.min(5,flatScale*f)),ratio=next/flatScale;flatX=x-(x-flatX)*ratio;flatY=y-(y-flatY)*ratio;flatScale=next;updateFlat();}
$('#flat').addEventListener('wheel',e=>{e.preventDefault();const r=area.getBoundingClientRect();zoom(e.deltaY<0?1.1:1/1.1,e.clientX-r.left,e.clientY-r.top);},{passive:false});$('#flat').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag=[e.clientX,e.clientY,flatX,flatY];$('#flat').setPointerCapture(e.pointerId);});$('#flat').addEventListener('pointermove',e=>{if(drag){flatX=drag[2]+e.clientX-drag[0];flatY=drag[3]+e.clientY-drag[1];updateFlat();}});$('#flat').addEventListener('pointerup',()=>drag=null);$('#flat').addEventListener('pointercancel',()=>drag=null);
campuses.forEach((c,i)=>{const b=document.createElement('button');b.textContent=c.name;b.onclick=()=>changeCampus(i);$('#campus-tabs').append(b);});$('#search').oninput=()=>{list();updateFlat();};$('#view3d').onclick=()=>setMode('3d');$('#view2d').onclick=()=>setMode('2d');$('#zoom-in').onclick=()=>zoom(1.2);$('#zoom-out').onclick=()=>zoom(1/1.2);$('#reset').onclick=()=>mode==='3d'?reset():resetFlat();$('#sources-button').onclick=()=>$('#sources').showModal();$('#close-sources').onclick=()=>$('#sources').close();$('#sources').addEventListener('click',e=>{if(e.target===$('#sources')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('#source-list').innerHTML=sources.map(s=>`<div class="source-row"><a href="${s.url}" target="_blank" rel="noopener">${s.title} ↗</a><small>${s.publisher} · ${s.date}</small><p>${s.use}</p></div>`).join('')+`<div class="source-row"><b>完整官方地图文件</b>${campuses.map(c=>`<p><a href="assets/${c.image}" target="_blank" rel="noopener">${c.name}完整原图 ↗</a>${c.compare?` · <a href="assets/${c.compare}" target="_blank" rel="noopener">2026迎新图对照 ↗</a>`:''}</p>`).join('')}</div>`;
init3d();changeCampus(0);
